-- Tables will be created by Hibernate (spring.jpa.hibernate.ddl-auto=update)

-- Insert a test user if one doesn't already exist (needed for the login test)
INSERT INTO app_user (email, password, role)
VALUES (
    'docker-test@cibf.com',
    -- **IMPORTANT:** REPLACE THIS HASH WITH ONE GENERATED BY YOUR APP'S ENCODER!
    '$2a$10$Q78K/J4rU0V6vB4N4h8s8uWq3C9.y.9/5s3qT2n/G2d8tH9jK8lP0',
    'VENDOR'
)
ON CONFLICT (email) DO NOTHING;